spring:
  application:
    name: category-manager-tgbot
  datasource:
    url: jdbc:postgresql://localhost:5432/Pandev-telegram-bot-tree
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

bot:
  name: ${TG_BOT_NAME:Pandev-telegram-bot-tree}
  token: ${TG_BOT_TOKEN:7615638841:AAG4WWJ8Sx27z4d2uv0e1TzQvaMqesjsIMs}
