package com.ramazanmamyrbek.categorymanagertgbot.models;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a category in the system. Each category can have a unique name
 * and may be associated with a parent category, allowing for hierarchical
 * relationships between categories.
 */
@Entity
@Table(name = "category")
@Getter
@Setter
@EqualsAndHashCode
@ToString(exclude = {"parent"})
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /**
     * Unique identifier for the category.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category.
     * Must be unique and cannot be null.
     */
    @Column(name = "name", unique = true, nullable = false)
    private String name;

    /**
     * The parent category of this category.
     * This establishes a hierarchical relationship between categories.
     */
    @ManyToOne
    @JoinColumn(name = "parent_id")
    private Category parent;

    /**
     * List of child categories associated with this category.
     * The relationship is bidirectional, and orphan removal is enabled
     * to automatically remove children if they are no longer referenced.
     */
    @OneToMany(mappedBy = "parent", orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Category> children = new ArrayList<>();

}
